### ISSUE TITLE
How to find the gene name that corresponds to the gene index in SL_data file?

### ISSUE THREAD

**Issue by karenyun** [JieZheng-ShanghaiTech/KG4SL#1]
Hi, I have a question about the SL_data file.

How do you find the gene name corresponding to the gene index in SL_data file? 
I download the Human_SL.csv, but the gene index of SL gene pair is not the same as the SL_data. How do you make the data in SL_data file?

Thanks very much!

**Comment by shikew** [comment]
Hi, 

Thanks for your interest. 

Due to updates in the SynLethDB, the gene index in the SL_data file may not match the gene index in the Human_SL.csv file that you downloaded. You can use the latest version of the SL data provided by SynLethDB.

**Comment by shikew** [comment]
Hi,

Thanks for your interest.

Due to updates in the SynLethDB, the gene index in the SL_data file may not match the gene index in the Human_SL.csv file that you downloaded. You can use the latest version of the SL data provided by SynLethDB.

**Comment by karenyun** [comment]
Hi @shikew , thanks very much!

What about the ID in the kg_triplet.csv? How can I align the index in the kg_triplet with the new SynLethDB?

**Comment by shikew** [comment]
To align the index with the latest SL data in SynLethDB, you can use the kg data available at https://synlethdb.sist.shanghaitech.edu.cn/#/download:~:text=sldb_complete_triple.csv. Note that the provided kg_triplet.csv here is not the latest version and shares the same index as SL_data file.

**Comment by karenyun** [comment]
Thanks very much! It is helpful!
